---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
```{r}
library(igraph)
library(tidyverse)
```

### Read data file
```{r}
#read file in as members
mt_edgelist <- read.csv("../data cleaning/all-data.csv")
View(mt_edgelist)
head(mt_edgelist)
```
Note: the sender is in the first column and receiver in the second




```{r}
#Careful, this overcounts!  The 'text' field is truncated for retweets, need to load
#new data file that includes sourcetweet_text field
JointMath<-mt_edgelist[mt_edgelist$user_username == 'JointMath',]
#did not use any of the hashtags or did not include a @JointMath tag
NotHT20<-subset(JointMath, !grepl("#JMM2020", JointMath$sourcetweet_text ), )
NotHT<-subset(NotHT20, !grepl("#JMM2021", NotHT20$sourcetweet_text ), )
Notpinged<-subset(NotHT, !grepl("@JointMath", NotHT$sourcetweet_text ))

# for example - this has nothing that says RT me...
Notpinged$text[12]
Notpinged
```

Clearly the JointMath handle was RTing JMM tweets



# What are our top group tweeting about?
```{r}
influencer_names = c("WanderingPoint","mathprofcarrie","sbagley","pwr2dppl","RG1gal","LoboWithACause","VictorPiercey1")
#influencers <- filter(mt_edgelist, user_username %in% influencer_names)

codes <- colnames(mt_edgelist)[54:88]

for (person in influencer_names) {
  influencers <- filter(mt_edgelist, user_username == person)
  #Drop retweets
  influencersOTQT <- filter(influencers, sourcetweet_type == "quoted" | is.na(sourcetweet_type))
  
  n=nrow(influencersOTQT)
  influencer_tweets <- c()
  cnames <- c()
  for (code in codes) {
    freq=length(which(influencersOTQT[code]=="True"))/n
    if (freq>0){ 
      influencer_tweets <- append(influencer_tweets,freq)
      cnames <- append(cnames,code)}
  }

names(influencer_tweets) <- cnames
influencer_tweets <- sort(influencer_tweets,decreasing=TRUE)
print(person)
print(n)
print(knitr::kable(influencer_tweets))
cat("\n\n")
}
```



```{r}
#What was @JointMath tweeting about?
jointmath <- filter(mt_edgelist, user_username == "JointMath")
n=nrow(jointmath)
codes <- colnames(jointmath)[54:88]
joint_tweets <- c()
for (code in codes) {
  joint_tweets <- append(joint_tweets, length(which(jointmath[code]=="True"))/n)
}
names(joint_tweets) <- codes
joint_tweets <- sort(joint_tweets,decreasing=TRUE)
print(joint_tweets)
print(n)
```

# Who is tweeting about important things?
```{r}
important_codes <- c("representation","gender","indigenous","advocacy","power","bipoc")

for (code in important_codes){
  code_only <- filter(mt_edgelist, (!!as.symbol(code))=="True")
  print(code)
  top_tweeters=sort(table(code_only$user_username),decreasing=TRUE)
  #print(head(top_tweeters,10))
  barplot(head(top_tweeters,10),las=2)
}



```


