---
title: "Data Analysis"
output: 
  html_document:
    code_folding: hide
date: "2023-01-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
# packages
library(tidyverse) 
library(tidytext) 
library(rtweet)
library(ggplot2)
library(knitr)

#Read in file
DisruptCoded<-read.csv("./Final Coding.csv")


#set up a summary dataframe and store theme counts and frequencies
Themes<-c("Self organization", "Building community","Broadening the counterpublic", "Creating change in math", "SJEDI")
Nper<-c(sum(DisruptCoded$Self.organization), sum(DisruptCoded$Building.community), sum(DisruptCoded$Broadening.the.counterpublic), sum(DisruptCoded$Creating.change.in.math), sum(DisruptCoded$SJEDI))
Freqper <- Nper/nrow(DisruptCoded)
ThemeSummary<-data.frame(Nper, Freqper)
row.names(ThemeSummary)<-Themes

#Examine only the non-RT
#original content tweets (OCT) are original tweets (OT), replies, and quote tweets (QT) 
whichRT<-str_detect(DisruptCoded$text, "^RT ")
OCT<-filter(DisruptCoded,!whichRT)
NperOCT<-c(sum(OCT$Self.organization), sum(OCT$Building.community), sum(OCT$Broadening.the.counterpublic), sum(OCT$Creating.change.in.math), sum(OCT$SJEDI))
FreqperOCT <- NperOCT/nrow(OCT)
ThemeSummary <- cbind(ThemeSummary, NperOCT, FreqperOCT)
```

How many tweets were in each bucket?
```{r}
kable(ThemeSummary, col.names=c("Number of tweets", "Frequency of tweets", "Number of original tweets", "Frequency of original tweets"),digits=c(0,2,0,2,0))
```

```{r}
#Tweet subsets of each code
SOtweets<-filter(DisruptCoded,Self.organization == 1)
BCtweets<-filter(DisruptCoded,Building.community == 1)
BtCtweets<-filter(DisruptCoded,Broadening.the.counterpublic == 1)
CCtweets<-filter(DisruptCoded,Creating.change.in.math == 1)
SJtweets<-filter(DisruptCoded,SJEDI == 1)

#TimeSeries of Tweets by hours
#DisruptCoded<-cbind(DisruptCoded, time <- as.POSIXct(strptime(DisruptCoded$created_at, "%a, %d %b %Y %H:%M:%S %z", tz = "GMT")))

```

Let's compute the frequency of the tags
```{r}
SOtags <- c("amplification", "activation", "strategic planning", "SO impact", "troll")
SOtagCount <- data.frame(sapply(SOtags, function(tag) return(nrow(filter(OCT,grepl(tag,SO.code))))))
colnames(SOtagCount)[1] <- "Number"
SOtagCount['Bucket']="Self Organization"

BCtags <- c("thankful", "talk support", "belonging", "emotional support", "expertise support", "conversation", "celebration", "BC impact")
BCtagCount <- data.frame(sapply(BCtags, function(tag) return(nrow(filter(OCT,grepl(tag,BC.code))))))
colnames(BCtagCount)[1] <- "Number"
BCtagCount['Bucket']="Building Community"

BtCtags <- c("disrupteverything", "influencers", "beyond", "hashtags", "virtual participation")
BtCtagCount <- data.frame(sapply(BtCtags, function(tag) return(nrow(filter(OCT,grepl(tag,BtC.code))))))
colnames(BtCtagCount)[1] <- "Number"
BtCtagCount['Bucket']="Broadening the Counterpublic"

CCMtags <- c("humanize", "jmm experience", "math experience", "futures", "math practice", "current events", "allyship in math", "CC impact")
CCMtagCount <- data.frame(sapply(CCMtags, function(tag) return(nrow(filter(OCT,grepl(tag,CCM.code))))))
colnames(CCMtagCount)[1] <- "Number"
CCMtagCount['Bucket']="Creating Change in Math"

SJEDItags<-c("representation", "lgbtq", "bipoc", "gender", "indigenous", "power", "advocacy", "learning", "economic", "SJEDI impact")
SJEDItagCount <- data.frame(sapply(SJEDItags, function(tag) return(nrow(filter(OCT,grepl(tag,SJEDI.code))))))
colnames(SJEDItagCount)[1] <- "Number"
SJEDItagCount['Bucket']="SJEDI"

TagCounts <- rbind(SOtagCount, BCtagCount, BtCtagCount, CCMtagCount, SJEDItagCount)
TagCounts <- cbind(TagCounts, TagCounts$Number/nrow(OCT))
colnames(TagCounts)[3] <- "Frequency"
kable(TagCounts[order(TagCounts$Number,decreasing=TRUE),c(2,1,3)], digits=c(0,0,2))
```

What can we say about coincidence of tags?
```{r}
tags=c(SOtags,BCtags,BtCtags,CCMtags,SJEDItags)
```
